language: java
sudo: false # faster builds
services:
  - xvfb

before_script:
  - "export DISPLAY=:99.0"
  
after_success:
  - ./gradlew jacocoTestReport coveralls
  - bash <(curl -s https://codecov.io/bash)
